<?php

return [

    'models' => [
        'permission' => Spatie\Permission\Models\Permission::class,
        'role' => App\Models\Role::class,
    ],

    'table_names' => [
        'roles' => 'roles',
        'permissions' => 'permissions',
        'model_has_permissions' => 'model_has_permissions',
        'model_has_roles' => 'model_has_roles',
        'role_has_permissions' => 'role_has_permissions',
    ],

    'column_names' => [
        'role_pivot_key' => null,
        'permission_pivot_key' => null,
        'model_morph_key' => 'model_id',
        'team_foreign_key' => 'team_id',
    ],

    'register_permission_check_method' => true,
    'register_octane_reset_listener' => false,
    'events_enabled' => false,
    'teams' => false,
    'team_resolver' => \Spatie\Permission\DefaultTeamResolver::class,
    'use_passport_client_credentials' => false,
    'display_permission_in_exception' => false,
    'display_role_in_exception' => false,
    'enable_wildcard_permission' => false,

    'cache' => [
        'expiration_time' => \DateInterval::createFromDateString('24 hours'),
        'key' => 'spatie.permission.cache',
        'store' => 'default',
    ],

    /*
     * Web permissions configuration
     * Centralized array of all web permissions organized by groups
     */
    'web_permissions' => [
        'dashboard' => [
            'view_dashboard',
            'charts',
            'statistics',
            'recent_activities',
        ],
        'branches' => [
            'view_branches',
            'request_branches',
            'edit_branches',
            'delete_branches'
        ],
        'terminals' => [
            'view_terminals',
            'create_terminals',
            'edit_terminals',
            'delete_terminals'
        ],
        'terminal_groups' => [
            'view_terminal_assignments',
            'edit_terminal_assignments',
            'delete_terminal_assignments',
            'assign_terminals',
        ],
        'settings' => [
            'view_settings',
            'create_settings',
            'edit_settings',
            'delete_settings'
        ],
        'users' => [
            'view_users',	
            'create_users',
            'edit_users',
            'delete_users',
            'activate_users',
            'deactivate_users',
            'reset_password',
        ],
        'users_groups' => [
            'view_users_groups',
            'create_users_groups',
            'edit_users_groups',
            'delete_users_groups', 
            'add_users_to_groups',
            'remove_users_from_groups', 
        ],
        'roles' => [
            'view_roles',
            'create_roles',
            'edit_roles',
            'delete_roles',
            'assign_roles',
        ],
        'transactions' => [
            'view_transactions',
            'view_transaction',
            'delete_transactions',
            'void_transactions',
            'refund_transactions',
            'view_transactions_history',
        ],
        'settlements' => [
            'view_settlements',
        ],
        'batches' => [
            'view_batches',
        ],
        'link_payments' => [
            'view_link_payments',
            'create_link_payments',
            'edit_link_payments',
            'delete_link_payments',
        ],
        'payment_links' => [
            'view_payment_links',
            'create_payment_links',
            'edit_payment_links',
            'delete_payment_links',
        ],
        'customers' => [
            'view_customers',
            'create_customers',
            'edit_customers',
            'delete_customers',
        ],
        'reports_management' => [
            'view_reports',
        ],
        'attachments_management' => [
            'show_attachments',
            'delete_attachments'
        ],
        'notifications' => [
            'view_notifications',
            'delete_notifications'
        ],
        'contract_terms' => [
            'view_contract_terms',
        ],
        'services_fees' => [
            'view_services_fees',
        ], 
    ],

    // Merchant Permissions (POS + Sales modules)
    'merchant_permissions' => [
        'pos_permissions' => [
            'dashboard' => [
                'view_dashboard',
                'view_statistics',
                'view_charts',
            ],
            'transactions' => [
                'view',
                'view_transactions',
                'create_transactions',
                'void_transactions',
                'refund_transactions',
                'view_transaction_details',
            ],
            'settlements' => [
                'view_settlements',
                'download_settlements',
            ],
            'batches' => [
                'view', 
                'view_batches',
                'close_batches',
            ],
            'terminals' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_terminals',
                'create_terminals',
                'edit_terminals',
                'delete_terminals',
                'assign_terminals',
            ],
            'branches' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_branches',
                'create_branches',
                'edit_branches',
                'delete_branches',
            ],
            'payment_links' => [
                'create', 
                'delete',
                'edit',
                'view_payment_links',
                'create_payment_links',
                'edit_payment_links',
                'delete_payment_links',
            ],
            'users' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_users',
                'create_users',
                'edit_users',
                'delete_users',
                'activate_users',
                'deactivate_users',
            ],
            'users_groups' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_users_group',
                'create_users_group',
                'edit_users_group',
                'delete_users_group',
                'activate_users_group',
                'deactivate_users_group',
            ],
            'roles' => [
                'create', 
                'delete',
                'edit',
                'view',
                'assign',
                'view_roles',
                'create_roles',
                'edit_roles',
                'delete_roles',
                'assign_roles',
            ],
            'reports' => [
                'view_reports',
                'export_reports',
            ],
            'service_fees' => [
                'view_service_fees',
                'view_services_fees',
            ],
            'contract_terms' => [
                'view_contract_terms',
            ],
        ],
        'sales_permissions' => [
            'dashboard' => [
                'view_sales_dashboard',
                'view_sales_statistics',
                'view_sales_charts',
            ],
            'customers' => [
                'view_customers',
                'view1_customers',
                'create_customers',
                'edit_customers',
                'delete_customers',
                'import_customers',
                'export_customers',
            ],
            'products' => [
                'view_products',
                'create_products',
                'edit_products',
                'delete_products',
                'import_products',
                'export_products',
            ],
            'categories' => [
                'view_categories',
                'create_categories',
                'edit_categories',
                'delete_categories',
            ],
            'tags' => [
                'view_tags',
                'create_tags',
                'edit_tags',
                'delete_tags',
            ],
            'brands' => [
                'view_brands',
                'create_brands',
                'edit_brands',
                'delete_brands',
            ],
            'units' => [
                'view_units',
                'create_units',
                'edit_units',
                'delete_units',
            ],
            'taxes' => [
                'view_taxes',
                'create_taxes',
                'edit_taxes',
                'delete_taxes',
            ],
            'warehouse' => [
                'view_warehouse',
                'manage_inventory',
                'adjust_stock',
                'transfer_stock',
            ],
            'orders' => [
                'view_orders',
                'create_orders',
                'edit_orders',
                'cancel_orders',
                'process_orders',
            ],
            'sales' => [
                'create_sales',
                'view_sales',
                'return_sales',
                'void_sales',
            ],
            'branches' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_branches',
                'create_branches',
                'edit_branches',
                'delete_branches',
            ],
            'users' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_users',
                'create_users',
                'edit_users',
                'delete_users',
                'activate_users',
                'deactivate_users',
            ],
            'users_groups' => [
                'create', 
                'delete',
                'edit',
                'view',
                'view_users_group',
                'create_users_group',
                'edit_users_group',
                'delete_users_group',
                'activate_users_group',
                'deactivate_users_group',
            ],
            'roles' => [
                'create', 
                'delete',
                'edit',
                'view',
                'assign',
                'view_roles',
                'create_roles',
                'edit_roles',
                'delete_roles',
                'assign_roles',
            ],
            'service_fees' => [
                'view_service_fees',
                'view_services_fees',
            ],
            'contract_terms' => [
                'view_contract_terms',
            ],
            'reports' => [
                'view_sales_reports',
                'view_product_reports',
                'view_inventory_reports',
                'export_sales_reports',
            ],
            'payment_gateways' => [
                'view_payment_gateways',
                'create_payment_gateways',
                'edit_payment_gateways',
                'delete_payment_gateways',
            ],
        ],
    ],
    // Admin Permissions (POS + Sales modules) - separate from merchant
    'admin_permissions' => [
        'pos_permissions' => [
            'dashboard' => [
                'view_dashboard',
                'view_statistics',
                'view_charts',
            ],
            'transactions' => [
                'view_transactions',
                'create_transactions',
                'void_transactions',
                'refund_transactions',
                'view_transaction_details',
            ],
            'settlements' => [
                'view_settlements',
                'download_settlements',
            ],
            'batches' => [
                'view_batches',
                'close_batches',
            ],
            'terminals' => [
                'view_terminals',
                'create_terminals',
                'edit_terminals',
                'delete_terminals',
                'assign_terminals',
            ],
            'branches' => [
                'view_branches',
                'create_branches',
                'edit_branches',
                'delete_branches',
            ],
            'users' => [
                'view_users',
                'create_users',
                'edit_users',
                'delete_users',
                'activate_users',
                'deactivate_users',
            ],
            'roles' => [
                'view_roles',
                'create_roles',
                'edit_roles',
                'delete_roles',
                'assign_roles',
            ],
            'reports' => [
                'view_reports',
                'export_reports',
            ],
            'merchants' => [
                'view_merchants',
                'create_merchants',
                'edit_merchants',
                'delete_merchants',
                'view_merchant_change_requests',
                'approve_merchants',
                'reject_merchants',
                'suspend_merchants',
                'unsuspend_merchants',
            ],
            'user_groups' => [
                'view_users_groups',
                'create_users_groups',
                'edit_users_groups',
                'delete_users_groups',
                'add_users_to_groups',
                'remove_users_from_groups',
            ],
            'terminal_groups' => [
                'view_terminal_assignments',
                'edit_terminal_assignments',
                'delete_terminal_assignments',
                'assign_terminals',
            ],
            'payment_links' => [
                'view_payment_links',
                'create_payment_links',
                'edit_payment_links',
                'delete_payment_links',
            ],
            'service_fees' => [
                'view_service_fees',
                'view_services_fees',
            ],
            'contract_terms' => [
                'view_contract_terms',
            ],
            'admins' => [
                'view_admins',
                'create_admins',
                'edit_admins',
                'delete_admins',
            ],
            'countries' => [
                'view_countries',
                'create_countries',
                'edit_countries',
                'delete_countries',
            ],
            'cities' => [
                'view_cities',
                'create_cities',
                'edit_cities',
                'delete_cities',
            ],
            'advertisements' => [
                'view_advertisements',
                'create_advertisements',
                'edit_advertisements',
                'delete_advertisements',
            ],
            'currencies' => [
                'view_currencies',
                'create_currencies',
                'edit_currencies',
                'delete_currencies',
            ],
        ],
        'sales_permissions' => [
            'dashboard' => [
                'view_sales_dashboard',
                'view_sales_statistics',
                'view_sales_charts',
            ],
            'customers' => [
                'view_customers',
                'create_customers',
                'edit_customers',
                'delete_customers',
                'import_customers',
                'export_customers',
            ],
            'products' => [
                'view_products',
                'create_products',
                'edit_products',
                'delete_products',
                'import_products',
                'export_products',
            ],
            'categories' => [
                'view_categories',
                'create_categories',
                'edit_categories',
                'delete_categories',
            ],
            'tags' => [
                'view_tags',
                'create_tags',
                'edit_tags',
                'delete_tags',
            ],
            'brands' => [
                'view_brands',
                'create_brands',
                'edit_brands',
                'delete_brands',
            ],
            'units' => [
                'view_units',
                'create_units',
                'edit_units',
                'delete_units',
            ],
            'taxes' => [
                'view_taxes',
                'create_taxes',
                'edit_taxes',
                'delete_taxes',
            ],
            'warehouse' => [
                'view_warehouse',
                'manage_inventory',
                'adjust_stock',
                'transfer_stock',
            ],
            'orders' => [
                'view_orders',
                'create_orders',
                'edit_orders',
                'cancel_orders',
                'process_orders',
            ],
            'sales' => [
                'create_sales',
                'view_sales',
                'return_sales',
                'void_sales',
            ],
            'purchases' => [
                'view_purchases',
                'create_purchases',
                'edit_purchases',
                'delete_purchases',
            ],
            'reports' => [
                'view_sales_reports',
                'view_product_reports',
                'view_inventory_reports',
                'export_sales_reports',
            ],
        ],
    ],
];
